name: ci

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/shiguredo/erlang:otp-28.4.2-openssl-3.6.2-ubuntu-26.04-x86_64
    steps:
      - uses: actions/checkout@v4
      - run: make compile dialyzer test

  notify:
    needs: [ci]
    if: always()
    runs-on: ubuntu-slim
    permissions:
      actions: read
      contents: read
    steps:
      - uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_channel: ${{ secrets.SLACK_INTERNAL_CHANNEL }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
