name: ci

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: shiguredo/shiguredo-erlang:otp-26.0.2-openssl-3.1.2-ubuntu-22.04-x86_64
    steps:
      - uses: actions/checkout@v4
      - run: make compile dialyzer test
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_INTERNAL_CHANNEL }}
          SLACK_COLOR: danger
          SLACK_TITLE: Failure test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
