on:
  push:
    paths-ignore:
    - 'LICENSE'
    - '**.md'

jobs:
  main:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'skip ci')"
    container:
      image: shiguredo/erlang:otp-23.1.2-ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make compile dialyzer test
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
